=== ayan4m1/vast-ai-provisioner/module.schema.json
{
  "$id": "https://raw.githubusercontent.com/ayan4m1/vast-ai-provisioner/main/module.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Module",
  "type": "object",
  "description": "A set of resources for a template",
  "properties": {
    "name": {
      "description": "The short name for the module",
      "type": "string",
      "exclusiveMinimum": 0
    },
    "description": {
      "description": "The long description for the module",
      "type": "string"
    },
    "gated": {
      "description": "Requires a Hugging Face token to download",
      "type": "boolean"
    },
    "template": {
      "description": "The template that this module is meant for",
      "type": "string",
      "exclusiveMinimum": 0
    },
    "files": {
      "description": "An object with lists of URLs for type of file exposed by the template",
      "type": "object",
      "exclusiveMinimum": 0,
      "patternProperties": {
        "^[a-z0-9_]+$": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": ["name", "template", "files"]
}

=== ayan4m1/vast-ai-provisioner/modules/flux-3-klein.json
{
  "$schema": "https://raw.githubusercontent.com/ayan4m1/vast-ai-provisioner/main/module.schema.json",
  "name": "Flux 3 Klein",
  "template": "ComfyUI",
  "gated": true,
  "files": {
    "diffusion_models": [
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/diffusion_models/flux3-image-klein-base-int8-convrot.safetensors",
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/diffusion_models/flux3-image-klein-int8-convrot.safetensors"
    ],
    "text_encoder_models": [
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/text_encoders/qwen3.5_9b_flux3_prompt_upsampler_int8_convrot.safetensors",
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/text_encoders/qwen3vl_4b_int8_convrot.safetensors"
    ],
    "vae_models": [
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/vae/flux2-vae.safetensors"
    ],
    "nodes": [],
    "workflows": [
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/workflows/flux3_klein_base_int8_i2i.json",
      "https://huggingface.co/black-forest-labs/flux-3-image-klein-comfy/resolve/main/workflows/flux3_klein_base_int8_t2i.json"
    ]
  }
}
